# Generated by Django 3.0.4 on 2020-03-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
